packages:
  - 'lib'
  - 'examples'
  - 'tests/*'
  - 'extension'

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  lefthook: true

minimumReleaseAge: 4320

overrides:
  serialize-javascript: '>=7.0.5'
