// Auto-generated by lines-db
// Do not edit this file manually

import { schema as customersSchema } from './customers.schema.js';
import { schema as ordersWithFkSchema } from './orders-with-fk.schema.js';
import { schema as ordersSchema } from './orders.schema.js';
import { schema as productsSchema } from './products.schema.js';
import { schema as testMigrateSchema } from './test-migrate.schema.js';
import { schema as usersSchema } from './users.schema.js';
import type { DatabaseConfig, InferOutput } from '@toiroakr/lines-db';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export type Tables = {
  customers: InferOutput<typeof customersSchema>;
  'error-output': Record<string, unknown>;
  'orders-with-fk': InferOutput<typeof ordersWithFkSchema>;
  orders: InferOutput<typeof ordersSchema>;
  products: InferOutput<typeof productsSchema>;
  'test-migrate': InferOutput<typeof testMigrateSchema>;
  users: InferOutput<typeof usersSchema>;
};

export const config: DatabaseConfig<Tables> = {
  dataDir: __dirname,
};
